local styles = {}

styles.default = {
    main_frame = {
        background = Color3.fromRGB(75, 0, 0),
        backgroundtransparency = 0.05,
        cornerRadius = 2,
        stroke = {
            color = Color3.fromRGB(0, 0, 0),
            thickness = 2,
            strokeMode = Enum.ApplyStrokeMode.Border,
            lineJoinMode = Enum.LineJoinMode.Round,
        },
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(75, 75, 75)),
                ColorSequenceKeypoint.new(0.25, Color3.fromRGB(150, 150, 150)),
                ColorSequenceKeypoint.new(0.75, Color3.fromRGB(150, 150, 150)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(75, 75, 75)),
            }),
            Rotation = 90,
        },
        anchorPoint = Vector2.new(0.5, 0.5),
        size = UDim2.new(0, 500, 0, 500),
        position = UDim2.new(0.5, 0, 0.5, 0),
    },
    topbar = {
        background = Color3.fromRGB(75, 0, 0),
        backgroundtransparency = 0.05,
        cornerRadius = 2,
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(150, 150, 150)),
            }),
            Rotation = 90,
        },
        anchorPoint = Vector2.new(0.5, 0),
        size = UDim2.new(1, 0, 0, 35),
        position = UDim2.new(0.5, 0, 0, 0),
    },
    windowtitle = {
        textColor = Color3.fromRGB(255, 255, 255),
        textSize = 16,
        textFont = Enum.Font.RobotoMono,
        textalignment = Enum.TextXAlignment.Left,
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(150, 150, 150)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(255, 255, 255)),
            }),
            Rotation = 0,
        },
        padding = {
            bottom = UDim.new(0, 0),
            left = UDim.new(0, 15),
            right = UDim.new(0, 0),
            top = UDim.new(0, 0),
        },
        anchorPoint = Vector2.new(0, 0.5),
        size = UDim2.new(1, 0, 0, 35),
        position = UDim2.new(0, 0, 0.5, 0),
    },
    tab_buttons = {
        background = Color3.fromRGB(255, 255, 255),
        backgroundtransparency = 1,
        anchorPoint = Vector2.new(0.5, 0),
        size = UDim2.new(1, 0, 0, 30),
        position = UDim2.new(0.5, 0, 0.07, 0),
        listlayout = {
            padding = UDim.new(0, 10),
            fillDirection = Enum.FillDirection.Horizontal,
            horizontalAlignment = Enum.HorizontalAlignment.Left,
            verticalAlignment = Enum.VerticalAlignment.Center,
        },
    },
    tab_button = {
        anchorPoint = Vector2.new(0.5, 0.5),
        size = UDim2.new(0, 75, 0, 30),
        textFont = Enum.Font.RobotoMono,
        textSize = 14,
        textXAlignment = Enum.TextXAlignment.Center,
        textYAlignment = Enum.TextYAlignment.Center,
        off = {
            textColor = Color3.fromRGB(150, 150, 150),
            gradient = {
                ColorSequence = ColorSequence.new({
                    ColorSequenceKeypoint.new(0, Color3.fromRGB(150, 150, 150)),
                    ColorSequenceKeypoint.new(
                        1.0,
                        Color3.fromRGB(255, 255, 255)
                    ),
                }),
                Rotation = 45,
            },
            padding = {
                bottom = UDim.new(0, 0),
                left = UDim.new(0, 10),
                right = UDim.new(0, 10),
                top = UDim.new(0, 0),
            },
        },
        on = {
            textColor = Color3.fromRGB(255, 255, 255),
            gradient = {
                ColorSequence = ColorSequence.new({
                    ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
                    ColorSequenceKeypoint.new(
                        1.0,
                        Color3.fromRGB(150, 150, 150)
                    ),
                }),
                Rotation = 90,
            },
        },
        hover = {
            textColor = Color3.fromRGB(255, 255, 255),
            gradient = {
                ColorSequence = ColorSequence.new({
                    ColorSequenceKeypoint.new(0, Color3.fromRGB(200, 200, 200)),
                    ColorSequenceKeypoint.new(
                        1.0,
                        Color3.fromRGB(255, 255, 255)
                    ),
                }),
                Rotation = 90,
            },
            padding = {
                bottom = UDim.new(0, 5),
                left = UDim.new(0, 10),
                right = UDim.new(0, 10),
                top = UDim.new(0, 0),
            },
        },
    },
    indicator = {
        background = Color3.fromRGB(150, 0, 0),
        anchorPoint = Vector2.new(0.5, 0.5),
        size = UDim2.new(1, 0, 0, 2),
        position = UDim2.new(0.5, 0, 1, 0),
        automaticSize = Enum.AutomaticSize.X,
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(75, 75, 75)),
                ColorSequenceKeypoint.new(0.25, Color3.fromRGB(150, 150, 150)),
                ColorSequenceKeypoint.new(0.75, Color3.fromRGB(150, 150, 150)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(75, 75, 75)),
            }),
            Rotation = 0,
        },
    },
    tabcontainer = {
        background = Color3.fromRGB(255, 255, 255),
        backgroundtransparency = 1,
        anchorPoint = Vector2.new(0.5, 0),
        size = UDim2.new(0, 500, 0, 435),
        position = UDim2.new(0.5, 0, 0.13, 0),
        padding = {
            bottom = UDim.new(0, 0),
            left = UDim.new(0, 0),
            right = UDim.new(0, 0),
            top = UDim.new(0, 10),
        },
    },
    tabsection = {
        background = Color3.fromRGB(255, 255, 255),
        backgroundtransparency = 1,
        anchorPoint = Vector2.new(0.5, 0),
        automaticSize = Enum.AutomaticSize.Y,
        size = UDim2.new(0, 250, 0, 100),
        listlayout = {
            padding = UDim.new(0, 8),
            fillDirection = Enum.FillDirection.Vertical,
            horizontalAlignment = Enum.HorizontalAlignment.Center,
            verticalAlignment = Enum.VerticalAlignment.Top,
        },
        left = {
            position = UDim2.new(0.25, 0, 0, 0),
            padding = {
                bottom = UDim.new(0, 0),
                left = UDim.new(0, 2),
                right = UDim.new(0, 0),
                top = UDim.new(0, 0),
            },
        },
        right = {
            position = UDim2.new(0.75, 0, 0, 0),
            padding = {
                bottom = UDim.new(0, 0),
                left = UDim.new(0, 0),
                right = UDim.new(0, 2),
                top = UDim.new(0, 0),
            },
        },
    },
    card = {
        background = Color3.fromRGB(50, 0, 0),
        backgroundtransparency = 0.5,
        anchorPoint = Vector2.new(0.5, 0.5),
        size = UDim2.new(0, 240, 0, 50),
        automaticSize = Enum.AutomaticSize.Y,
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(75, 75, 75)),
                ColorSequenceKeypoint.new(0.25, Color3.fromRGB(150, 150, 150)),
                ColorSequenceKeypoint.new(0.75, Color3.fromRGB(150, 150, 150)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(75, 75, 75)),
            }),
            Rotation = 90,
        },
        stroke = {
            color = Color3.fromRGB(25, 0, 0),
            thickness = 2,
            strokeMode = Enum.ApplyStrokeMode.Contextual,
            lineJoinMode = Enum.LineJoinMode.Round,
        },
        listlayout = {
            padding = UDim.new(0, 4),
            fillDirection = Enum.FillDirection.Vertical,
            horizontalAlignment = Enum.HorizontalAlignment.Center,
            verticalAlignment = Enum.VerticalAlignment.Top,
        },
    },
    cardtitle = {
        textColor = Color3.fromRGB(255, 255, 255),
        textSize = 14,
        textFont = Enum.Font.RobotoMono,
        textalignment = Enum.TextXAlignment.Left,
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(150, 150, 150)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(255, 255, 255)),
            }),
            Rotation = 0,
        },
        padding = {
            bottom = UDim.new(0, 10),
            left = UDim.new(0, 10),
            right = UDim.new(0, 10),
            top = UDim.new(0, 10),
        },
        anchorPoint = Vector2.new(0, 0.5),
        size = UDim2.new(1, 0, 0, 25),
        position = UDim2.new(0, 0, 0.5, 0),
    },
    cardcontent = {
        size = UDim2.new(1, 0, 0, 30),
        anchorPoint = Vector2.new(0.5, 0.5),
        automaticSize = Enum.AutomaticSize.Y,
        listlayout = {
            padding = UDim.new(0, 4),
            fillDirection = Enum.FillDirection.Vertical,
            horizontalAlignment = Enum.HorizontalAlignment.Center,
            verticalAlignment = Enum.VerticalAlignment.Top,
        },
        padding = {
            bottom = UDim.new(0, 4),
            left = UDim.new(0, 0),
            right = UDim.new(0, 0),
            top = UDim.new(0, 0),
        },
    },
    richTextLabel = {
        textColor = Color3.fromRGB(255, 255, 255),
        textSize = 14,
        textFont = Enum.Font.RobotoMono,
        textalignment = Enum.TextXAlignment.Left,
        richText = true,
        automaticSize = Enum.AutomaticSize.Y,
        padding = {
            bottom = UDim.new(0, 0),
            left = UDim.new(0, 10),
            right = UDim.new(0, 10),
            top = UDim.new(0, 0),
        },
        size = UDim2.new(1, 0, 0, 30),
        anchorPoint = Vector2.new(0.5, 0.5),
    },
    button = {
        singlewide = {
            frame = {
                size = UDim2.new(0, 240, 0, 30),
                anchorPoint = Vector2.new(0.5, 0.5),
            },
            background = Color3.fromRGB(25, 0, 0),
            backgroundTransparency = 0.75,
            anchorPoint = Vector2.new(0.5, 0.5),
            position = UDim2.new(0.5, 0, 0.5, 0),
            automaticSize = Enum.AutomaticSize.Y,
            size = UDim2.new(0, 220, 0, 25),
            textColor = Color3.fromRGB(255, 255, 255),
            textSize = 14,
            textFont = Enum.Font.RobotoMono,
            textAlignment = Enum.TextXAlignment.Center,
        },
        subtext = {
            richTextLabel = {
                textColor = Color3.fromRGB(255, 255, 255),
                textSize = 12,
                textFont = Enum.Font.RobotoMono,
                textalignment = Enum.TextXAlignment.Left,
                richText = true,
                padding = {
                    bottom = UDim.new(0, 0),
                    left = UDim.new(0, 10),
                    right = UDim.new(0, 10),
                    top = UDim.new(0, 0),
                },
                size = UDim2.new(0, 115, 0, 30),
                position = UDim2.new(0.25, 0, 0.5, 0),
                anchorPoint = Vector2.new(0.5, 0.5),
            },
            frame = {
                size = UDim2.new(0, 240, 0, 60),
                anchorPoint = Vector2.new(0.5, 0.5),
            },
            background = Color3.fromRGB(25, 0, 0),
            backgroundTransparency = 0.75,
            anchorPoint = Vector2.new(0.5, 0.5),
            position = UDim2.new(0.724, 0, 0.5, 0),
            automaticSize = Enum.AutomaticSize.Y,
            size = UDim2.new(0, 110, 0, 25),
            textColor = Color3.fromRGB(255, 255, 255),
            textSize = 14,
            textFont = Enum.Font.RobotoMono,
            textAlignment = Enum.TextXAlignment.Center,
            cornerRadius = 2,
            stroke = {
                color = Color3.fromRGB(25, 0, 0),
                thickness = 2,
                strokeMode = Enum.ApplyStrokeMode.Border,
                lineJoinMode = Enum.LineJoinMode.Round,
            },
        },
    },
}
-- Explicit dark theme table mirroring styles.default structure
styles.dark = {
    main_frame = {
        background = Color3.fromRGB(20, 20, 20),
        backgroundtransparency = 0,
        cornerRadius = 2,
        stroke = {
            color = Color3.fromRGB(0, 0, 0),
            thickness = 2,
            strokeMode = Enum.ApplyStrokeMode.Border,
            lineJoinMode = Enum.LineJoinMode.Round,
        },
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(30, 30, 30)),
                ColorSequenceKeypoint.new(0.25, Color3.fromRGB(45, 45, 45)),
                ColorSequenceKeypoint.new(0.75, Color3.fromRGB(45, 45, 45)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(30, 30, 30)),
            }),
            Rotation = 90,
        },
        anchorPoint = Vector2.new(0.5, 0.5),
        size = UDim2.new(0, 500, 0, 500),
        position = UDim2.new(0.5, 0, 0.5, 0),
    },
    topbar = {
        background = Color3.fromRGB(28, 28, 28),
        backgroundtransparency = 0,
        cornerRadius = 2,
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(200, 200, 200)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(140, 140, 140)),
            }),
            Rotation = 90,
        },
        anchorPoint = Vector2.new(0.5, 0),
        size = UDim2.new(1, 0, 0, 35),
        position = UDim2.new(0.5, 0, 0, 0),
    },
    windowtitle = {
        textColor = Color3.fromRGB(255, 255, 255),
        textSize = 16,
        textFont = Enum.Font.RobotoMono,
        textalignment = Enum.TextXAlignment.Left,
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(180, 180, 180)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(255, 255, 255)),
            }),
            Rotation = 0,
        },
        padding = {
            bottom = UDim.new(0, 0),
            left = UDim.new(0, 15),
            right = UDim.new(0, 0),
            top = UDim.new(0, 0),
        },
        anchorPoint = Vector2.new(0, 0.5),
        size = UDim2.new(1, 0, 0, 35),
        position = UDim2.new(0, 0, 0.5, 0),
    },
    tab_buttons = {
        background = Color3.fromRGB(255, 255, 255),
        backgroundtransparency = 1,
        anchorPoint = Vector2.new(0.5, 0),
        size = UDim2.new(1, 0, 0, 30),
        position = UDim2.new(0.5, 0, 0.07, 0),
        listlayout = {
            padding = UDim.new(0, 10),
            fillDirection = Enum.FillDirection.Horizontal,
            horizontalAlignment = Enum.HorizontalAlignment.Left,
            verticalAlignment = Enum.VerticalAlignment.Center,
        },
    },
    tab_button = {
        anchorPoint = Vector2.new(0.5, 0.5),
        size = UDim2.new(0, 75, 0, 30),
        textFont = Enum.Font.RobotoMono,
        textSize = 14,
        textXAlignment = Enum.TextXAlignment.Center,
        textYAlignment = Enum.TextYAlignment.Center,
        off = {
            textColor = Color3.fromRGB(160, 160, 160),
            gradient = {
                ColorSequence = ColorSequence.new({
                    ColorSequenceKeypoint.new(0, Color3.fromRGB(120, 120, 120)),
                    ColorSequenceKeypoint.new(1.0, Color3.fromRGB(210, 210, 210)),
                }),
                Rotation = 45,
            },
            padding = {
                bottom = UDim.new(0, 0),
                left = UDim.new(0, 10),
                right = UDim.new(0, 10),
                top = UDim.new(0, 0),
            },
        },
        on = {
            textColor = Color3.fromRGB(255, 255, 255),
            gradient = {
                ColorSequence = ColorSequence.new({
                    ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
                    ColorSequenceKeypoint.new(1.0, Color3.fromRGB(170, 170, 170)),
                }),
                Rotation = 90,
            },
        },
        hover = {
            textColor = Color3.fromRGB(255, 255, 255),
            gradient = {
                ColorSequence = ColorSequence.new({
                    ColorSequenceKeypoint.new(0, Color3.fromRGB(200, 200, 200)),
                    ColorSequenceKeypoint.new(1.0, Color3.fromRGB(255, 255, 255)),
                }),
                Rotation = 90,
            },
            padding = {
                bottom = UDim.new(0, 5),
                left = UDim.new(0, 10),
                right = UDim.new(0, 10),
                top = UDim.new(0, 0),
            },
        },
    },
    indicator = {
        background = Color3.fromRGB(200, 30, 30),
        anchorPoint = Vector2.new(0.5, 0.5),
        size = UDim2.new(1, 0, 0, 2),
        position = UDim2.new(0.5, 0, 1, 0),
        automaticSize = Enum.AutomaticSize.X,
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(60, 60, 60)),
                ColorSequenceKeypoint.new(0.25, Color3.fromRGB(120, 120, 120)),
                ColorSequenceKeypoint.new(0.75, Color3.fromRGB(120, 120, 120)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(60, 60, 60)),
            }),
            Rotation = 0,
        },
    },
    tabcontainer = {
        background = Color3.fromRGB(255, 255, 255),
        backgroundtransparency = 1,
        anchorPoint = Vector2.new(0.5, 0),
        size = UDim2.new(0, 500, 0, 435),
        position = UDim2.new(0.5, 0, 0.13, 0),
        padding = {
            bottom = UDim.new(0, 0),
            left = UDim.new(0, 0),
            right = UDim.new(0, 0),
            top = UDim.new(0, 10),
        },
    },
    tabsection = {
        background = Color3.fromRGB(255, 255, 255),
        backgroundtransparency = 1,
        anchorPoint = Vector2.new(0.5, 0),
        automaticSize = Enum.AutomaticSize.Y,
        size = UDim2.new(0, 250, 0, 100),
        listlayout = {
            padding = UDim.new(0, 8),
            fillDirection = Enum.FillDirection.Vertical,
            horizontalAlignment = Enum.HorizontalAlignment.Center,
            verticalAlignment = Enum.VerticalAlignment.Top,
        },
        left = {
            position = UDim2.new(0.25, 0, 0, 0),
            padding = {
                bottom = UDim.new(0, 0),
                left = UDim.new(0, 2),
                right = UDim.new(0, 0),
                top = UDim.new(0, 0),
            },
        },
        right = {
            position = UDim2.new(0.75, 0, 0, 0),
            padding = {
                bottom = UDim.new(0, 0),
                left = UDim.new(0, 0),
                right = UDim.new(0, 2),
                top = UDim.new(0, 0),
            },
        },
    },
    card = {
        background = Color3.fromRGB(28, 28, 28),
        backgroundtransparency = 0.15,
        anchorPoint = Vector2.new(0.5, 0.5),
        size = UDim2.new(0, 240, 0, 50),
        automaticSize = Enum.AutomaticSize.Y,
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(40, 40, 40)),
                ColorSequenceKeypoint.new(0.25, Color3.fromRGB(70, 70, 70)),
                ColorSequenceKeypoint.new(0.75, Color3.fromRGB(70, 70, 70)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(40, 40, 40)),
            }),
            Rotation = 90,
        },
        stroke = {
            color = Color3.fromRGB(50, 50, 50),
            thickness = 2,
            strokeMode = Enum.ApplyStrokeMode.Contextual,
            lineJoinMode = Enum.LineJoinMode.Round,
        },
        listlayout = {
            padding = UDim.new(0, 4),
            fillDirection = Enum.FillDirection.Vertical,
            horizontalAlignment = Enum.HorizontalAlignment.Center,
            verticalAlignment = Enum.VerticalAlignment.Top,
        },
    },
    cardtitle = {
        textColor = Color3.fromRGB(255, 255, 255),
        textSize = 14,
        textFont = Enum.Font.RobotoMono,
        textalignment = Enum.TextXAlignment.Left,
        gradient = {
            ColorSequence = ColorSequence.new({
                ColorSequenceKeypoint.new(0, Color3.fromRGB(160, 160, 160)),
                ColorSequenceKeypoint.new(1.0, Color3.fromRGB(255, 255, 255)),
            }),
            Rotation = 0,
        },
        padding = {
            bottom = UDim.new(0, 10),
            left = UDim.new(0, 10),
            right = UDim.new(0, 10),
            top = UDim.new(0, 10),
        },
        anchorPoint = Vector2.new(0, 0.5),
        size = UDim2.new(1, 0, 0, 25),
        position = UDim2.new(0, 0, 0.5, 0),
    },
    cardcontent = {
        size = UDim2.new(1, 0, 0, 30),
        anchorPoint = Vector2.new(0.5, 0.5),
        automaticSize = Enum.AutomaticSize.Y,
        listlayout = {
            padding = UDim.new(0, 4),
            fillDirection = Enum.FillDirection.Vertical,
            horizontalAlignment = Enum.HorizontalAlignment.Center,
            verticalAlignment = Enum.VerticalAlignment.Top,
        },
        padding = {
            bottom = UDim.new(0, 4),
            left = UDim.new(0, 0),
            right = UDim.new(0, 0),
            top = UDim.new(0, 0),
        },
    },
    richTextLabel = {
        textColor = Color3.fromRGB(255, 255, 255),
        textSize = 14,
        textFont = Enum.Font.RobotoMono,
        textalignment = Enum.TextXAlignment.Left,
        richText = true,
        automaticSize = Enum.AutomaticSize.Y,
        padding = {
            bottom = UDim.new(0, 0),
            left = UDim.new(0, 10),
            right = UDim.new(0, 10),
            top = UDim.new(0, 0),
        },
        size = UDim2.new(1, 0, 0, 30),
        anchorPoint = Vector2.new(0.5, 0.5),
    },
    button = {
        singlewide = {
            frame = {
                size = UDim2.new(0, 240, 0, 30),
                anchorPoint = Vector2.new(0.5, 0.5),
            },
            background = Color3.fromRGB(36, 36, 36),
            backgroundTransparency = 0.2,
            anchorPoint = Vector2.new(0.5, 0.5),
            position = UDim2.new(0.5, 0, 0.5, 0),
            automaticSize = Enum.AutomaticSize.Y,
            size = UDim2.new(0, 220, 0, 25),
            textColor = Color3.fromRGB(255, 255, 255),
            textSize = 14,
            textFont = Enum.Font.RobotoMono,
            textAlignment = Enum.TextXAlignment.Center,
        },
        subtext = {
            richTextLabel = {
                textColor = Color3.fromRGB(255, 255, 255),
                textSize = 12,
                textFont = Enum.Font.RobotoMono,
                textalignment = Enum.TextXAlignment.Left,
                richText = true,
                padding = {
                    bottom = UDim.new(0, 0),
                    left = UDim.new(0, 10),
                    right = UDim.new(0, 10),
                    top = UDim.new(0, 0),
                },
                size = UDim2.new(0, 115, 0, 30),
                position = UDim2.new(0.25, 0, 0.5, 0),
                anchorPoint = Vector2.new(0.5, 0.5),
            },
            frame = {
                size = UDim2.new(0, 240, 0, 60),
                anchorPoint = Vector2.new(0.5, 0.5),
            },
            background = Color3.fromRGB(36, 36, 36),
            backgroundTransparency = 0.2,
            anchorPoint = Vector2.new(0.5, 0.5),
            position = UDim2.new(0.724, 0, 0.5, 0),
            automaticSize = Enum.AutomaticSize.Y,
            size = UDim2.new(0, 110, 0, 25),
            textColor = Color3.fromRGB(255, 255, 255),
            textSize = 14,
            textFont = Enum.Font.RobotoMono,
            textAlignment = Enum.TextXAlignment.Center,
            cornerRadius = 2,
            stroke = {
                color = Color3.fromRGB(58, 58, 58),
                thickness = 2,
                strokeMode = Enum.ApplyStrokeMode.Border,
                lineJoinMode = Enum.LineJoinMode.Round,
            },
        },
    },
}

return styles
